/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Fuente = new javax.swing.JMenu();
        Arial = new javax.swing.JMenuItem();
        Serif = new javax.swing.JMenuItem();
        Verdana = new javax.swing.JMenuItem();
        Estilo = new javax.swing.JMenu();
        Negrita = new javax.swing.JMenuItem();
        Cursiva = new javax.swing.JMenuItem();
        Tamaño = new javax.swing.JMenu();
        Texto12 = new javax.swing.JMenuItem();
        Texto16 = new javax.swing.JMenuItem();
        Texto18 = new javax.swing.JMenuItem();
        Texto20 = new javax.swing.JMenuItem();
        Archivo = new javax.swing.JMenu();
        Guardar = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto.setToolTipText("");
        jScrollPane2.setViewportView(Texto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 640, 350));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROCESADOR DE TEXTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo procesador.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 650, 450));

        Fuente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fuente.setText("FUENTE");

        Arial.setText("Arial");
        Fuente.add(Arial);

        Serif.setText("Serif");
        Fuente.add(Serif);

        Verdana.setText("Verdana");
        Fuente.add(Verdana);

        jMenuBar1.add(Fuente);

        Estilo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Estilo.setText("ESTILO");

        Negrita.setText("Negrita");
        Estilo.add(Negrita);

        Cursiva.setText("Cursiva");
        Cursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursivaActionPerformed(evt);
            }
        });
        Estilo.add(Cursiva);

        jMenuBar1.add(Estilo);

        Tamaño.setBackground(new java.awt.Color(204, 204, 255));
        Tamaño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tamaño.setText("TAMAÑO");

        Texto12.setText("12");
        Tamaño.add(Texto12);

        Texto16.setText("16");
        Texto16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto16ActionPerformed(evt);
            }
        });
        Tamaño.add(Texto16);

        Texto18.setText("18");
        Tamaño.add(Texto18);

        Texto20.setText("20");
        Tamaño.add(Texto20);

        jMenuBar1.add(Tamaño);

        Archivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Archivo.setText("ARCHIVO");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);

        Abrir.setText("Abrir");
        Archivo.add(Abrir);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursivaActionPerformed

    private void Texto16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto16ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem Abrir;
    public javax.swing.JMenu Archivo;
    public javax.swing.JMenuItem Arial;
    public javax.swing.JMenuItem Cursiva;
    private javax.swing.JMenu Estilo;
    public javax.swing.JMenu Fuente;
    public javax.swing.JMenuItem Guardar;
    public javax.swing.JMenuItem Negrita;
    public javax.swing.JMenuItem Serif;
    private javax.swing.JMenu Tamaño;
    public javax.swing.JTextPane Texto;
    public javax.swing.JMenuItem Texto12;
    public javax.swing.JMenuItem Texto16;
    public javax.swing.JMenuItem Texto18;
    public javax.swing.JMenuItem Texto20;
    public javax.swing.JMenuItem Verdana;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
